### ISSUE TITLE
Warn when account information of a persistent session is changed

### ISSUE THREAD

**Issue by kivattik** [rackerlabs/mimic#151] opened 2015-01-19 22:42 UTC
In order to improve the the user experience, Mimic should provide a warning if the user attempts to use a different tenant_id or username in a persistent session. For example, if a persistent session exists with username = testuser1 and tenant_id=1234, and a new authentication is attempted with testuser1 and tenant_id=5678, the user should get a message stating that user1 previously authenticated as tenant 1234. 

Note: The persistent session behavior is intended, and the circumstances leading to this type of confusion are likely uncommon, but I think that an informative warning could prove useful for people developing against mimic.

**Comment by glyph** [comment] 2015-01-19 22:47
I think is a duplicate of #146 ?

**Comment by glyph** [comment] 2015-01-19 22:47
(Please reopen if not.)

**Closed by glyph** 2015-01-19 22:47 UTC
Labels: duplicate, enhancement
